### ISSUE TITLE
URL uninitialized constant GitMirror

### ISSUE THREAD

**Issue by liamdemafelix** [linniksa/redmine_git_mirror#1]
I tried linking a repository of mine on GitHub to a project and after saving it just gives me `URL uninitialized constant GitMirror`.

![screencapture-projects-xdg-ph-projects-sample-project-repositories-2019-01-31-11_06_13](https://user-images.githubusercontent.com/798476/52027982-43fc6c00-2548-11e9-867d-798feaa3f25a.png)

Any ideas? If you need a log file please let me know. I'm not really well-versed in Ruby so I don't know where to start looking.

**Comment by linniksa** [comment]
What versions of redmail, ruby, rails are you using? 
You can look it on `redmine.site/admin/info`

**Comment by linniksa** [comment]
I cannot  reproduce this, but can you test on new version from [`master`](/linniksa/redmine_git_mirror/tree/master) branch and on [`test-autoload`](/linniksa/redmine_git_mirror/tree/test-autoload) branch.

**Comment by linniksa** [comment]
Hello, this issue is fixed for you?
Can you tell how? Issues #2 #3 maybe have same cause and decision with this one
