### ISSUE TITLE
Gitea-Support

### ISSUE THREAD

**Issue by sharpSteff** [linniksa/redmine_git_mirror#10]
We are switching to the open source git service gitea (https://gitea.io/en-us/) and like to use `Redmine Git Mirror plugin `to synchronize our git repos with redmine.

In case this feature is not planned, I like to contribute it myself.

**Comment by linniksa** [comment]
looks like you can use current `github` receiver, see https://docs.gitea.io/en-us/webhooks/ 
if you want to contribute, can you check and add instructions for gitea to the readme?

**Comment by sharpSteff** [comment]
you're right, the github receiver might work.
i'll check that. 

Thanks for the quick reply

**Comment by flozzone** [comment]
The github receiver reads a github specific event header. The one for gitea is different. See PR #23 which addresses this.

**Comment by linniksa** [comment]
https://github.com/go-gitea/gitea/blob/9659808172b0d33a79eca44e37cabaf33fbf1b8b/services/webhook/deliver.go#L101
gitea sends github header to
