### ISSUE TITLE
plugin configuration URL schemes doesn't work 

### ISSUE THREAD

**Issue by sadeshwar94** [linniksa/redmine_git_mirror#2]
![image](https://user-images.githubusercontent.com/30549368/52192723-dffede00-288e-11e9-99e6-e3afa918f595.png)
after checking & applying "permitted URL schemes" the values won't be updated.

**Comment by linniksa** [comment]
What version of redmine, ruby, rails? You can look this info on `redmine.site/admin/info`

**Comment by sadeshwar94** [comment]
Hi, I'm sorry for the late reply, following are the information of my Redmine environment : 
Environment:
  Redmine version             3.4.1.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                    4.2.8
  Environment                   production
  Database adapter            Mysql2

**Comment by linniksa** [comment]
Hello, can you test latest version of master branch?

**Comment by sadeshwar94** [comment]
![image](https://user-images.githubusercontent.com/30549368/52933118-8bcb2200-3395-11e9-86c4-cb14b8957d8f.png)

Hi, i have done the testing using the latest version of the master branch, now im getting the above error when a connection using HTTP , or either way using SSH i get the redmine 500 erorr. 
for an example, my https URL will be as follows, 
ex; https://username:password@gitlaburl/gpname/projectname.git

**Comment by linniksa** [comment]
Hi,
storing credentials in url is not allowed because full url stored as-is in repo config, at this moment preferred way is to use ssh for private repos.
I have idea how to implements password auth but not have time at this moment.
About 500 for ssh - can you test `test-autoload` branch?

**Comment by sadeshwar94** [comment]
Hi, i have tested with the test-autload brach as well and using SSH i still get the same resutls, 
here's the production log error,


Started GET "/projects/drj-000/repositories/new?repository_scm=GitMirror" for 183.77.119.104 at 2019-02-18 18:03:28 +0900
Processing by RepositoriesController#new as JS
  Parameters: {"repository_scm"=>"GitMirror", "project_id"=>"drj-000"}
  Current user: sadesh (id=21)
  Rendered repositories/_form.html.erb (3.0ms)
  Rendered repositories/new.html.erb (53.6ms)
  Rendered repositories/new.js.erb (54.7ms)
Completed 200 OK in 171ms (Views: 154.6ms | ActiveRecord: 3.1ms)
Started POST "/projects/drj-000/repositories" for 183.77.119.104 at 2019-02-18 18:03:38 +0900
Processing by RepositoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"TJsP1LjHnXxXRxcn9IzGBHYw+2Iq5NU/58w66cU1jy0cQe2K2T66ELmqnUpO5TxePgKvgHLnq1DkcsdkTPt6Eg==", "repository_scm"=>"GitMir$
  Current user: sadesh (id=21)
Completed 500 Internal Server Error in 27ms (ActiveRecord: 3.7ms)

**Comment by linniksa** [comment]
can you check https://github.com/linniksa/redmine_git_mirror/tree/deps branch?
